### ISSUE TITLE
Numerous vulnerabilities and missing dependencies

### ISSUE THREAD

**Issue by rohancl** [scorelab/drola#55]
FIX: https://github.com/scorelab/drola/pull/54

1. Cron was missing from the dependencies, causing a build fail.

![missing cron](https://user-images.githubusercontent.com/29266591/47966784-721efc80-e07c-11e8-8a5e-fbd942b1a356.png)

2. Outdated Versions

![vulneribilities](https://user-images.githubusercontent.com/29266591/47966807-b6120180-e07c-11e8-8fdf-0cb553bcb707.png)

3. Use of jade, which is officially deprecated. Pug is available as the official successor of jade,

**Comment by chamathsilva** [comment]
#54
